# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module UberApi
  class Driver < BaseModel
    # The first name of the driver.
    # @return [String]
    attr_accessor :name

    # The formatted phone number for contacting the driver.
    # @return [String]
    attr_accessor :phone_number

    # The URL to the photo of the driver.
    # @return [String]
    attr_accessor :picture_url

    # The driver's star rating out of 5 stars.
    # @return [Float]
    attr_accessor :rating

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["name"] = "name"
        @hash["phone_number"] = "phone_number"
        @hash["picture_url"] = "picture_url"
        @hash["rating"] = "rating"
      end
      @hash
    end

    def initialize(name = nil,
                   phone_number = nil,
                   picture_url = nil,
                   rating = nil)
      @name = name
      @phone_number = phone_number
      @picture_url = picture_url
      @rating = rating
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        name = hash["name"]
        phone_number = hash["phone_number"]
        picture_url = hash["picture_url"]
        rating = hash["rating"]

        # Create object from extracted values
        Driver.new(name,
                   phone_number,
                   picture_url,
                   rating)
      end
    end
  end
end
