# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module UberApi
  class Meta < BaseModel
    # TODO: Write general description for this method
    # @return [SurgeConfirmation]
    attr_accessor :surge_confirmation

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["surge_confirmation"] = "surge_confirmation"
      end
      @hash
    end

    def initialize(surge_confirmation = nil)
      @surge_confirmation = surge_confirmation
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        surge_confirmation = SurgeConfirmation.from_hash(hash["surge_confirmation"]) if hash["surge_confirmation"]

        # Create object from extracted values
        Meta.new(surge_confirmation)
      end
    end
  end
end
