# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module UberApi
  class PriceEstimateCollection < BaseModel
    # List of price estimates
    # @return [List of PriceEsitmate]
    attr_accessor :prices

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["prices"] = "prices"
      end
      @hash
    end

    def initialize(prices = nil)
      @prices = prices
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        # Parameter is an array, so we need to iterate through it
        prices = nil
        if hash["prices"] != nil
          prices = Array.new
          hash["prices"].each{|structure| prices << (PriceEsitmate.from_hash(structure) if structure)}
        end

        # Create object from extracted values
        PriceEstimateCollection.new(prices)
      end
    end
  end
end
