# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module UberApi
  class ProductCollection < BaseModel
    # List of products
    # @return [List of Product]
    attr_accessor :products

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["products"] = "products"
      end
      @hash
    end

    def initialize(products = nil)
      @products = products
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        # Parameter is an array, so we need to iterate through it
        products = nil
        if hash["products"] != nil
          products = Array.new
          hash["products"].each{|structure| products << (Product.from_hash(structure) if structure)}
        end

        # Create object from extracted values
        ProductCollection.new(products)
      end
    end
  end
end
