# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module UberApi
  class PromotionsResponse < BaseModel
    # A localized string we recommend to use when offering the promotion to users.
    # @return [String]
    attr_accessor :display_text

    # The value of the promotion that is available to a user in this location in the local currency.
    # @return [String]
    attr_accessor :localized_value

    # The type of the promo which is either "trip_credit" or "account_credit".
    # @return [String]
    attr_accessor :type

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["display_text"] = "display_text"
        @hash["localized_value"] = "localized_value"
        @hash["type"] = "type"
      end
      @hash
    end

    def initialize(display_text = nil,
                   localized_value = nil,
                   type = nil)
      @display_text = display_text
      @localized_value = localized_value
      @type = type
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        display_text = hash["display_text"]
        localized_value = hash["localized_value"]
        type = hash["type"]

        # Create object from extracted values
        PromotionsResponse.new(display_text,
                               localized_value,
                               type)
      end
    end
  end
end
