# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module UberApi
  class RequestMapResponse < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :href

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :request_id

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["href"] = "href"
        @hash["request_id"] = "request_id"
      end
      @hash
    end

    def initialize(href = nil,
                   request_id = nil)
      @href = href
      @request_id = request_id
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        href = hash["href"]
        request_id = hash["request_id"]

        # Create object from extracted values
        RequestMapResponse.new(href,
                               request_id)
      end
    end
  end
end
