# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module UberApi
  class SurgeConfirmation < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :href

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :surge_confirmation_id

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["href"] = "href"
        @hash["surge_confirmation_id"] = "surge_confirmation_id"
      end
      @hash
    end

    def initialize(href = nil,
                   surge_confirmation_id = nil)
      @href = href
      @surge_confirmation_id = surge_confirmation_id
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        href = hash["href"]
        surge_confirmation_id = hash["surge_confirmation_id"]

        # Create object from extracted values
        SurgeConfirmation.new(href,
                              surge_confirmation_id)
      end
    end
  end
end
