# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module UberApi
  class TimeEstimateCollection < BaseModel
    # List of time estimates
    # @return [List of TimeEstimate]
    attr_accessor :times

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["times"] = "times"
      end
      @hash
    end

    def initialize(times = nil)
      @times = times
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        # Parameter is an array, so we need to iterate through it
        times = nil
        if hash["times"] != nil
          times = Array.new
          hash["times"].each{|structure| times << (TimeEstimate.from_hash(structure) if structure)}
        end

        # Create object from extracted values
        TimeEstimateCollection.new(times)
      end
    end
  end
end
