# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module UberApi
  class UserProfile < BaseModel
    # Email address of the Uber user
    # @return [String]
    attr_accessor :email

    # First name of the Uber user.
    # @return [String]
    attr_accessor :first_name

    # Last name of the Uber user.
    # @return [String]
    attr_accessor :last_name

    # Image URL of the Uber user.
    # @return [String]
    attr_accessor :picture

    # Promo code of the Uber user.
    # @return [String]
    attr_accessor :promo_code

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["email"] = "email"
        @hash["first_name"] = "first_name"
        @hash["last_name"] = "last_name"
        @hash["picture"] = "picture"
        @hash["promo_code"] = "promo_code"
      end
      @hash
    end

    def initialize(email = nil,
                   first_name = nil,
                   last_name = nil,
                   picture = nil,
                   promo_code = nil)
      @email = email
      @first_name = first_name
      @last_name = last_name
      @picture = picture
      @promo_code = promo_code
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        email = hash["email"]
        first_name = hash["first_name"]
        last_name = hash["last_name"]
        picture = hash["picture"]
        promo_code = hash["promo_code"]

        # Create object from extracted values
        UserProfile.new(email,
                        first_name,
                        last_name,
                        picture,
                        promo_code)
      end
    end
  end
end
