# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module UberApi
  class Vehicle < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :license_plate

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :make

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :model

    # A mapping from model property names to API property names
    def self.names
      if @hash.nil?
        @hash = {}
        @hash["license_plate"] = "license_plate"
        @hash["make"] = "make"
        @hash["model"] = "model"
      end
      @hash
    end

    def initialize(license_plate = nil,
                   make = nil,
                   model = nil)
      @license_plate = license_plate
      @make = make
      @model = model
    end

    # Creates an instance of the object from a hash
    def self.from_hash(hash)
      if hash == nil
        nil
      else
        # Extract variables from the hash
        license_plate = hash["license_plate"]
        make = hash["make"]
        model = hash["model"]

        # Create object from extracted values
        Vehicle.new(license_plate,
                    make,
                    model)
      end
    end
  end
end
