# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
require 'json'
require 'faraday'
require 'certifi'
require 'logging'

require_relative 'uber_api/api_helper.rb'
require_relative 'uber_api/uber_api_client.rb'

# Http
require_relative 'uber_api/http/http_call_back.rb'
require_relative 'uber_api/http/http_client.rb'
require_relative 'uber_api/http/http_method_enum.rb'
require_relative 'uber_api/http/http_request.rb'
require_relative 'uber_api/http/http_response.rb'
require_relative 'uber_api/http/http_context.rb'
require_relative 'uber_api/http/faraday_client.rb'
require_relative 'uber_api/http/auth/basic_auth.rb'

# Models
require_relative 'uber_api/models/base_model.rb'
require_relative 'uber_api/models/errors.rb'
require_relative 'uber_api/models/request.rb'
require_relative 'uber_api/models/vehicle.rb'
require_relative 'uber_api/models/product.rb'
require_relative 'uber_api/models/time_estimate.rb'
require_relative 'uber_api/models/price_esitmate.rb'
require_relative 'uber_api/models/request_details_collections.rb'
require_relative 'uber_api/models/driver.rb'
require_relative 'uber_api/models/request_body.rb'
require_relative 'uber_api/models/location.rb'
require_relative 'uber_api/models/history.rb'
require_relative 'uber_api/models/user_activity.rb'
require_relative 'uber_api/models/user_profile.rb'
require_relative 'uber_api/models/promotions_response.rb'
require_relative 'uber_api/models/product_collection.rb'
require_relative 'uber_api/models/price_estimate_collection.rb'
require_relative 'uber_api/models/time_estimate_collection.rb'
require_relative 'uber_api/models/error_base.rb'
require_relative 'uber_api/models/meta.rb'
require_relative 'uber_api/models/surge_confirmation.rb'
require_relative 'uber_api/models/request_map_response.rb'

# Exceptions
require_relative 'uber_api/exceptions/api_exception.rb'

require_relative 'uber_api/configuration.rb'

# Controllers
require_relative 'uber_api/controllers/base_controller.rb'
require_relative 'uber_api/controllers/api_controller.rb'
