# This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).

module UberApi
  class UberAPIClient
    # Singleton access to client controller
    # @return [APIController] Returns the controller instance
    def client
      APIController.instance
    end

    # Initializer with authentication and configuration parameters
    def initialize(basic_auth_user_name: nil, basic_auth_password: nil)
      Configuration.basic_auth_user_name = basic_auth_user_name if basic_auth_user_name
      Configuration.basic_auth_password = basic_auth_password if basic_auth_password
    end
  end
end
